name: Check If Server Is Reachable

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Check server reachability
        run: curl -v https://kit.digitalauto.tech


    