name: Test Async Socket.IO

on:
    workflow_dispatch:

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install "python-socketio[asyncio]" aiohttp

      - name: Run async client
        run: python connect.py
